---
version: "3.8"
 
networks:
  temp-gateway:
    external: true
  temp-app:
    external: true
  temp-db: 
    external: true

volumes:
  mysql:
    driver: local


services:

  nginx:
    image: nginx:stable-alpine3.17-perl
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    tty: true
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - wordpress
      - mysql
    networks:
      - temp-gateway
      - temp-app

  wordpress: 
    build: 
      context: wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    hostname: wordpress
    restart: unless-stopped
    tty: true
    depends_on: 
      - mysql
    networks:
      - temp-app
      - temp-db
    environment:
      WORDPRESS_DB_HOST     : ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER     : ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD : ${WORDPRESS_DB_PASSWORD} 
      WORDPRESS_DB_NAME     : ${WORDPRESS_DB_NAME}

  mysql:
    image: mysql:5.6.51
    container_name: mysql
    hostname: mysql
    restart: unless-stopped
    tty: true
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - temp-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE:      ${MYSQL_DATABASE}    
      MYSQL_USER:          ${MYSQL_USER}         
      MYSQL_PASSWORD:      ${MYSQL_PASSWORD}

